name: Add Updated to README

on:
  pull_request_target:
    types:
      - closed
    branches:
      - main

jobs:
  update-by-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      # pull-requests: write
      # pages: write
      # id-token: write

    steps:
      - name: Checking out the repo
        uses: actions/checkout@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          
      - name: Add updated to README
        run: |
          echo "" >> README.md
          echo "${{ github.actor }}"  >> README.md
          echo "" >> README.md

      - name: Commit and Push
        run: |
          if [ "$(git status | grep 'Changes not staged\|Untracked files')" ]; then
            git diff
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git commit -am "Update README.md"
            git push origin main
          fi
