name: Add Updated to README

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          echo "\ndefault script test" >> README.md
          git add .
          git commit -m "Update README.md"
          git push
