name: Add Updated to README

on:
  push:
    branches:
      - main
 
permissions:
    contents: write

jobs:
  add-updated:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref }}
          
      - name: Add updated to README
        run: echo "Added Text" >> README.md
        
      - name: Commit and Push
        run: |
          if [ "$(git status | grep 'Changes not staged\|Untracked files')" ]; then
            git diff
            git config --global user.email "actions@github.com"
            git config --global user.name "GitHub Actions"
            git commit -am "Update README.md"
            git push
          fi
