name: Add Updated to README

on:
  push:
    branches:
      - main

jobs:
  add-updated:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
        
      - name: Adding Changes to README.md
        run: |
          echo "Added Text to README.md" >> README.md
          
      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Updated README.md by ${{ github.actor }}"
          
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
