name: Add Updated to README

on:
  push:
    branches:
      - main

jobs:
  add-updated:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Add updated to README
        run: echo "updated" >> README.md
      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -m "Add updated to README" README.md
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: iamwatchdogs/github-actions-test
          branch: main
